services:
  app:
    build:
      context: ./php-apache
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8275:80"
      - "9001:9001"
    volumes:
      - ../src:/var/www/html
      - ./php-apache/vhost.config:/etc/apache2/sites-available/000-default.conf
      - ./php-apache/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      XDEBUG_MODE: debug,develop # enable debug and develop features
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003" # Xdebug to connect to your IDE on port 9003
    depends_on:
      - db
      - rabbitmq
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    ports:
      - "3506:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  mailer:
    image: schickling/mailcatcher
    container_name: laravel_mailer
    ports:
      - 2025:1025
      - 2080:1080
    networks:
      - laravel

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # AMQP protocol port
      - "15672:15672"     # HTTP management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data:
  rabbitmq_data: